In [24]:
import pandas as pd
import numpy as np


In [25]:
df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/00471/Data_for_UCI_named.csv')


In [26]:
pd.options.display.max_columns=None

In [27]:
df.head()

tau1      tau2      tau3      tau4        p1        p2        p3  \
0  2.959060  3.079885  8.381025  9.780754  3.763085 -0.782604 -1.257395   
1  9.304097  4.902524  3.047541  1.369357  5.067812 -1.940058 -1.872742   
2  8.971707  8.848428  3.046479  1.214518  3.405158 -1.207456 -1.277210   
3  0.716415  7.669600  4.486641  2.340563  3.963791 -1.027473 -1.938944   
4  3.134112  7.608772  4.943759  9.857573  3.525811 -1.125531 -1.845975   

         p4        g1        g2        g3        g4      stab     stabf  
0 -1.723086  0.650456  0.859578  0.887445  0.958034  0.055347  unstable  
1 -1.255012  0.413441  0.862414  0.562139  0.781760 -0.005957    stable  
2 -0.920492  0.163041  0.766689  0.839444  0.109853  0.003471  unstable  
3 -0.997374  0.446209  0.976744  0.929381  0.362718  0.028871  unstable  
4 -0.554305  0.797110  0.455450  0.656947  0.820923  0.049860  unstable

In [28]:
df['stabf'].value_counts()

unstable    6380
stable      3620
Name: stabf, dtype: int64

In [29]:
df = df.drop(['stab'], axis=1)

In [30]:
df.head()

tau1      tau2      tau3      tau4        p1        p2        p3  \
0  2.959060  3.079885  8.381025  9.780754  3.763085 -0.782604 -1.257395   
1  9.304097  4.902524  3.047541  1.369357  5.067812 -1.940058 -1.872742   
2  8.971707  8.848428  3.046479  1.214518  3.405158 -1.207456 -1.277210   
3  0.716415  7.669600  4.486641  2.340563  3.963791 -1.027473 -1.938944   
4  3.134112  7.608772  4.943759  9.857573  3.525811 -1.125531 -1.845975   

         p4        g1        g2        g3        g4     stabf  
0 -1.723086  0.650456  0.859578  0.887445  0.958034  unstable  
1 -1.255012  0.413441  0.862414  0.562139  0.781760    stable  
2 -0.920492  0.163041  0.766689  0.839444  0.109853  unstable  
3 -0.997374  0.446209  0.976744  0.929381  0.362718  unstable  
4 -0.554305  0.797110  0.455450  0.656947  0.820923  unstable

In [31]:
X = df.drop(['stabf'], axis=1)
y = df['stabf']

In [32]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y , test_size=0.2, random_state=1)

print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(8000, 12)
(2000, 12)
(8000,)
(2000,)


In [33]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_sc = scaler.fit_transform(X_train)
X_test_sc = scaler.transform(X_test)


In [101]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

y_train = le.fit_transform(y_train)
y_test = le.fit_transform(y_test)

In [35]:
X_train_scaled = pd.DataFrame(X_train_sc, columns = X_train.columns)
X_test_scaled = pd.DataFrame(X_test_sc, columns = X_test.columns)

In [102]:
#Randomforest

from sklearn.ensemble import RandomForestClassifier

rfc = RandomForestClassifier(random_state=1)

rfc.fit(X_train_scaled, y_train)

RandomForestClassifier(random_state=1)

In [103]:
rf_pred = rfc.predict(X_test_scaled)

In [106]:
#performance metrics
from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score, confusion_matrix, classification_report
#model accuracy
def test_scores(preds):
    

    accuracy = accuracy_score(y_test, preds)
    print("Accuracy: ", round(accuracy,2))

    recall = recall_score(y_test, preds)
    print("Recall: ", round(recall,2))

    precision = precision_score(y_test, preds)
    print("Precision: ", round(precision,2))

    F1_score = f1_score(y_test, preds)
    print("F1_score: ", round(F1_score,2))

    cnf_matrix = confusion_matrix(y_test, preds)
    print('Confusion Matrix:\n', cnf_matrix)
    
    #classification report
    print('Classification Report:\n', classification_report(y_test,preds, digits =4))


In [88]:
accuracy = accuracy_score(y_test, rf_pred)
print("Accuracy: ", round(accuracy,5))

Accuracy:  0.929


In [107]:
test_scores(rf_pred)

Accuracy:  0.93
Recall:  0.96
Precision:  0.93
F1_score:  0.95
Confusion Matrix:
 [[ 625   87]
 [  55 1233]]
Classification Report:
               precision    recall  f1-score   support

           0     0.9191    0.8778    0.8980       712
           1     0.9341    0.9573    0.9456      1288

    accuracy                         0.9290      2000
   macro avg     0.9266    0.9176    0.9218      2000
weighted avg     0.9288    0.9290    0.9286      2000



In [108]:
print("Training set score: ",(rfc.score(X_train_scaled, y_train)))
print("Test set score: ",(rfc.score(X_test_scaled, y_test)))

Training set score:  1.0
Test set score:  0.929


In [109]:
# Extratrees Classifier

from sklearn.ensemble import ExtraTreesClassifier

etc = ExtraTreesClassifier(random_state = 1)


etc.fit(X_train_scaled, y_train)

ExtraTreesClassifier(random_state=1)

In [110]:
etc_pred = etc.predict(X_test_scaled)

In [111]:
test_scores(etc_pred)

Accuracy:  0.93
Recall:  0.97
Precision:  0.92
F1_score:  0.95
Confusion Matrix:
 [[ 606  106]
 [  38 1250]]
Classification Report:
               precision    recall  f1-score   support

           0     0.9410    0.8511    0.8938       712
           1     0.9218    0.9705    0.9455      1288

    accuracy                         0.9280      2000
   macro avg     0.9314    0.9108    0.9197      2000
weighted avg     0.9287    0.9280    0.9271      2000



In [112]:
print("Training set score: ",(etc.score(X_train_scaled, y_train)))
print("Test set score: ",(etc.score(X_test_scaled, y_test)))

Training set score:  1.0
Test set score:  0.928


In [119]:
#XGBoost

from xgboost import XGBClassifier

xgb = XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              learning_rate=0.1, max_delta_step=0, max_depth=3,
              min_child_weight=1, missing=None, n_estimators=100, n_jobs=1,
              nthread=None, objective='binary:logistic', random_state=1,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)

xgb.fit(X_train_scaled, y_train)

C:\Users\swati\anaconda3\lib\site-packages\xgboost\sklearn.py:888: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


[21:28:10] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.3.0/src/learner.cc:1061: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.1, max_delta_step=0, max_depth=3,
              min_child_weight=1, missing=None, monotone_constraints='()',
              n_estimators=100, n_jobs=1, nthread=1, num_parallel_tree=1,
              random_state=1, reg_alpha=0, reg_lambda=1, scale_pos_weight=1,
              seed=1, silent=None, subsample=1, tree_method='exact',
              validate_parameters=1, verbosity=1)

In [120]:
xgb_pred = xgb.predict(X_test_scaled)

In [121]:
test_scores(xgb_pred)

Accuracy:  0.92
Recall:  0.96
Precision:  0.92
F1_score:  0.94
Confusion Matrix:
 [[ 603  109]
 [  52 1236]]
Classification Report:
               precision    recall  f1-score   support

           0     0.9206    0.8469    0.8822       712
           1     0.9190    0.9596    0.9389      1288

    accuracy                         0.9195      2000
   macro avg     0.9198    0.9033    0.9105      2000
weighted avg     0.9195    0.9195    0.9187      2000



In [65]:
print("Training set score: ",(xgb.score(X_train_scaled, y_train)))
print("Test set score: ",(xgb.score(X_test_scaled, y_test)))



Training set score:  1.0
Test set score:  0.9455


In [123]:
#LightGBM

from lightgbm import LGBMClassifier

lgbm = LGBMClassifier(random_state = 1)

lgbm.fit(X_train_scaled, y_train)

LGBMClassifier(random_state=1)

In [124]:
lgbm_pred = lgbm.predict(X_test_scaled)

In [125]:
test_scores(lgbm_pred)

Accuracy:  0.94
Recall:  0.96
Precision:  0.95
F1_score:  0.95
Confusion Matrix:
 [[ 641   71]
 [  50 1238]]
Classification Report:
               precision    recall  f1-score   support

           0     0.9276    0.9003    0.9138       712
           1     0.9458    0.9612    0.9534      1288

    accuracy                         0.9395      2000
   macro avg     0.9367    0.9307    0.9336      2000
weighted avg     0.9393    0.9395    0.9393      2000



In [69]:
print("Training set score: ",(lgbm.score(X_train_scaled, y_train)))
print("Test set score: ",(lgbm.score(X_test_scaled, y_test)))

Training set score:  0.997875
Test set score:  0.9395


In [126]:
#Hyperparameter tuning of Extra Trees Classifier

n_estimators = [50, 100, 300, 500, 1000]

min_samples_split = [2, 3, 5, 7, 9]

min_samples_leaf = [1, 2, 4, 6, 8]

max_features = ['auto', 'sqrt', 'log2', None]

hyperparameter_grid = {'n_estimators': n_estimators,
                       'min_samples_leaf': min_samples_leaf,
                       'min_samples_split': min_samples_split,
                       'max_features': max_features}

In [127]:
from sklearn.model_selection import RandomizedSearchCV

randomcv = RandomizedSearchCV(estimator = etc,param_distributions = hyperparameter_grid,
                              cv=5, n_jobs = -1, verbose = 1,random_state = 1)

In [128]:
cv = randomcv.fit(X_train_scaled, y_train)

Fitting 5 folds for each of 10 candidates, totalling 50 fits


In [129]:
cv.best_params_

{'n_estimators': 1000,
 'min_samples_split': 2,
 'min_samples_leaf': 8,
 'max_features': None}

In [74]:
etc.feature_importances_

array([0.11739736, 0.11844468, 0.11316851, 0.11546569, 0.03950675,
       0.04037132, 0.04070628, 0.04057864, 0.08978291, 0.09367636,
       0.09688268, 0.09401882])

In [130]:
etc_improved = ExtraTreesClassifier(n_estimators= 1000,min_samples_split= 2,
                                    min_samples_leaf= 8,max_features= None, random_state=1)

In [131]:
etc_improved.fit(X_train_scaled,y_train)

ExtraTreesClassifier(max_features=None, min_samples_leaf=8, n_estimators=1000,
                     random_state=1)

In [132]:
etc_improved_pred = etc_improved.predict(X_test_scaled)

In [133]:
test_scores(etc_improved_pred)

Accuracy:  0.93
Recall:  0.96
Precision:  0.93
F1_score:  0.94
Confusion Matrix:
 [[ 619   93]
 [  53 1235]]
Classification Report:
               precision    recall  f1-score   support

           0     0.9211    0.8694    0.8945       712
           1     0.9300    0.9589    0.9442      1288

    accuracy                         0.9270      2000
   macro avg     0.9256    0.9141    0.9193      2000
weighted avg     0.9268    0.9270    0.9265      2000



In [134]:
etc_improved.feature_importances_

array([0.13723975, 0.1405075 , 0.13468029, 0.13541676, 0.00368342,
       0.00533686, 0.00542927, 0.00496249, 0.10256244, 0.10757765,
       0.11306268, 0.10954089])

In [135]:
X_train_scaled.head()

tau1      tau2      tau3      tau4        p1        p2        p3  \
0  0.367327 -0.986042  0.650447  1.547527 -0.291490  0.061535  1.293862   
1 -0.064659  0.089437  1.035079 -1.641494  0.619865 -0.067235 -1.502925   
2 -1.467850  1.298418 -0.502536  1.166046 -0.180521  0.490603  0.682560   
3  0.820081  0.529920  1.299657 -1.141975 -0.812854 -0.763632  1.521579   
4  0.665424 -1.425627  0.312300  0.919137 -1.614296  0.760315  1.422019   

         p4        g1        g2        g3        g4  
0 -0.845074  0.160918  0.339859  0.585568  0.492239  
1  0.486613 -0.293143 -1.558488  1.429649 -1.443521  
2 -0.855302  1.399350  1.451534 -1.045743  0.492489  
3  0.658780 -0.958319  1.361958  1.604140  0.275303  
4  0.639243  1.676895  0.695660  1.137504 -1.312575

In [86]:
print("Training set score: ",(etc_improved.score(X_train_scaled, y_train)))
print("Test set score: ",(etc_improved.score(X_test_scaled, y_test)))

Training set score:  0.98325
Test set score:  0.927
