In [1]:
import pandas as pd
import numpy as np

In [88]:
df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/00374/energydata_complete.csv')

In [4]:
pd.options.display.max_columns=None

In [5]:
df.head()

date  Appliances  lights     T1       RH_1    T2       RH_2  \
0  2016-01-11 17:00:00          60      30  19.89  47.596667  19.2  44.790000   
1  2016-01-11 17:10:00          60      30  19.89  46.693333  19.2  44.722500   
2  2016-01-11 17:20:00          50      30  19.89  46.300000  19.2  44.626667   
3  2016-01-11 17:30:00          50      40  19.89  46.066667  19.2  44.590000   
4  2016-01-11 17:40:00          60      40  19.89  46.333333  19.2  44.530000   

      T3       RH_3         T4       RH_4         T5   RH_5        T6  \
0  19.79  44.730000  19.000000  45.566667  17.166667  55.20  7.026667   
1  19.79  44.790000  19.000000  45.992500  17.166667  55.20  6.833333   
2  19.79  44.933333  18.926667  45.890000  17.166667  55.09  6.560000   
3  19.79  45.000000  18.890000  45.723333  17.166667  55.09  6.433333   
4  19.79  45.000000  18.890000  45.530000  17.200000  55.09  6.366667   

        RH_6         T7       RH_7    T8       RH_8         T9   RH_9  \
0  84.256667  17.200000  41.626667  18.2  48.900000  17.033333  45.53   
1  84.063333  17.200000  41.560000  18.2  48.863333  17.066667  45.56   
2  83.156667  17.200000  41.433333  18.2  48.730000  17.000000  45.50   
3  83.423333  17.133333  41.290000  18.1  48.590000  17.000000  45.40   
4  84.893333  17.200000  41.230000  18.1  48.590000  17.000000  45.40   

      T_out  Press_mm_hg  RH_out  Windspeed  Visibility  Tdewpoint        rv1  \
0  6.600000        733.5    92.0   7.000000   63.000000        5.3  13.275433   
1  6.483333        733.6    92.0   6.666667   59.166667        5.2  18.606195   
2  6.366667        733.7    92.0   6.333333   55.333333        5.1  28.642668   
3  6.250000        733.8    92.0   6.000000   51.500000        5.0  45.410389   
4  6.133333        733.9    92.0   5.666667   47.666667        4.9  10.084097   

         rv2  
0  13.275433  
1  18.606195  
2  28.642668  
3  45.410389  
4  10.084097

In [89]:
df = df.drop(['date','lights'],axis=1)

In [7]:
df.head()

Appliances     T1       RH_1    T2       RH_2     T3       RH_3         T4  \
0          60  19.89  47.596667  19.2  44.790000  19.79  44.730000  19.000000   
1          60  19.89  46.693333  19.2  44.722500  19.79  44.790000  19.000000   
2          50  19.89  46.300000  19.2  44.626667  19.79  44.933333  18.926667   
3          50  19.89  46.066667  19.2  44.590000  19.79  45.000000  18.890000   
4          60  19.89  46.333333  19.2  44.530000  19.79  45.000000  18.890000   

        RH_4         T5   RH_5        T6       RH_6         T7       RH_7  \
0  45.566667  17.166667  55.20  7.026667  84.256667  17.200000  41.626667   
1  45.992500  17.166667  55.20  6.833333  84.063333  17.200000  41.560000   
2  45.890000  17.166667  55.09  6.560000  83.156667  17.200000  41.433333   
3  45.723333  17.166667  55.09  6.433333  83.423333  17.133333  41.290000   
4  45.530000  17.200000  55.09  6.366667  84.893333  17.200000  41.230000   

     T8       RH_8         T9   RH_9     T_out  Press_mm_hg  RH_out  \
0  18.2  48.900000  17.033333  45.53  6.600000        733.5    92.0   
1  18.2  48.863333  17.066667  45.56  6.483333        733.6    92.0   
2  18.2  48.730000  17.000000  45.50  6.366667        733.7    92.0   
3  18.1  48.590000  17.000000  45.40  6.250000        733.8    92.0   
4  18.1  48.590000  17.000000  45.40  6.133333        733.9    92.0   

   Windspeed  Visibility  Tdewpoint        rv1        rv2  
0   7.000000   63.000000        5.3  13.275433  13.275433  
1   6.666667   59.166667        5.2  18.606195  18.606195  
2   6.333333   55.333333        5.1  28.642668  28.642668  
3   6.000000   51.500000        5.0  45.410389  45.410389  
4   5.666667   47.666667        4.9  10.084097  10.084097

In [8]:
from sklearn.preprocessing import MinMaxScaler

In [9]:
scaler = MinMaxScaler()
scaled_df = pd.DataFrame(scaler.fit_transform(df) , columns = df.columns)

In [10]:
scaled_df.head()

Appliances       T1      RH_1        T2      RH_2        T3      RH_3  \
0    0.046729  0.32735  0.566187  0.225345  0.684038  0.215188  0.746066   
1    0.046729  0.32735  0.541326  0.225345  0.682140  0.215188  0.748871   
2    0.037383  0.32735  0.530502  0.225345  0.679445  0.215188  0.755569   
3    0.037383  0.32735  0.524080  0.225345  0.678414  0.215188  0.758685   
4    0.046729  0.32735  0.531419  0.225345  0.676727  0.215188  0.758685   

         T4      RH_4        T5      RH_5        T6      RH_6        T7  \
0  0.351351  0.764262  0.175506  0.381691  0.381070  0.841827  0.170594   
1  0.351351  0.782437  0.175506  0.381691  0.375443  0.839872  0.170594   
2  0.344745  0.778062  0.175506  0.380037  0.367487  0.830704  0.170594   
3  0.341441  0.770949  0.175506  0.380037  0.363800  0.833401  0.164310   
4  0.341441  0.762697  0.178691  0.380037  0.361859  0.848264  0.170594   

       RH_7        T8      RH_8        T9      RH_9     T_out  Press_mm_hg  \
0  0.653428  0.173329  0.661412  0.223032  0.677290  0.372990     0.097674   
1  0.651064  0.173329  0.660155  0.226500  0.678532  0.369239     0.100000   
2  0.646572  0.173329  0.655586  0.219563  0.676049  0.365488     0.102326   
3  0.641489  0.164175  0.650788  0.219563  0.671909  0.361736     0.104651   
4  0.639362  0.164175  0.650788  0.219563  0.671909  0.357985     0.106977   

     RH_out  Windspeed  Visibility  Tdewpoint       rv1       rv2  
0  0.894737   0.500000    0.953846   0.538462  0.265449  0.265449  
1  0.894737   0.476190    0.894872   0.533937  0.372083  0.372083  
2  0.894737   0.452381    0.835897   0.529412  0.572848  0.572848  
3  0.894737   0.428571    0.776923   0.524887  0.908261  0.908261  
4  0.894737   0.404762    0.717949   0.520362  0.201611  0.201611

In [22]:
#Q12

x1 = scaled_df[['T2']].values
y1 = scaled_df['T6'].values

x1,y1

(array([[0.22534529],
        [0.22534529],
        [0.22534529],
        ...,
        [0.69265118],
        [0.67705355],
        [0.66617051]]),
 array([0.3810702 , 0.37544268, 0.36748654, ..., 0.86426042, 0.82952506,
        0.78858002]))

In [14]:
from sklearn.model_selection import train_test_split

In [23]:
x1_train, x1_test, y1_train, y1_test = train_test_split(x1,y1,random_state = 42, test_size=0.3)

In [24]:
print(x1_train.shape,
x1_test.shape,
y1_train.shape,
y1_test.shape)

(13814, 1) (5921, 1) (13814,) (5921,)


In [25]:
from sklearn.linear_model import LinearRegression

reg_1 = LinearRegression()
reg_1.fit(x1_train , y1_train)

LinearRegression()

In [26]:
y1_pred = reg_1.predict(x1_test)

In [29]:
from sklearn.metrics import r2_score

r2 = r2_score(y1_test, y1_pred)
print(round(r2,2))

0.64


In [30]:
#q13

from sklearn.metrics import mean_absolute_error

mae = mean_absolute_error(y1_test, y1_pred)

In [35]:
print(round(mae,2))

0.08


In [34]:
sum(abs(y1_test-y1_pred))/len(y1_test)

0.08216970202681702

In [39]:
#q14
rss = np.sum(np.square(y1_test-y1_pred))

In [41]:
print(round(rss,2))

66.12


In [42]:
#q15

rmse = np.sqrt(rss/len(y1_test))

In [43]:
print(round(rmse,3))

0.106


In [44]:
#q16 
print(round(r2,2))

0.64


In [90]:
#q17

y= scaled_df['Appliances'].values
x= scaled_df.drop(['Appliances'], axis=1).values

print(x.shape, y.shape)
print(df.shape)

(19735, 26) (19735,)
(19735, 27)


In [91]:
from sklearn.model_selection import train_test_split

x_train,x_test, y_train, y_test = train_test_split(x,y,random_state=42,test_size=0.3)

In [92]:
print(x_train.shape, y_train.shape, x_test.shape, y_test.shape)

(13814, 26) (13814,) (5921, 26) (5921,)


In [93]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression()

reg.fit(x_train,y_train)

LinearRegression()

In [94]:
columns = [ 'T1', 'RH_1', 'T2', 'RH_2', 'T3', 'RH_3', 'T4', 'RH_4',
       'T5', 'RH_5', 'T6', 'RH_6', 'T7', 'RH_7', 'T8', 'RH_8', 'T9', 'RH_9',
       'T_out', 'Press_mm_hg', 'RH_out', 'Windspeed', 'Visibility',
       'Tdewpoint', 'rv1', 'rv2']

In [95]:
imp = pd.DataFrame({'feature':columns, 'importance' :reg.coef_})

In [96]:

print(imp.sort_values('importance',ascending = False))

        feature  importance
1          RH_1    0.553547
4            T3    0.290627
10           T6    0.236425
23    Tdewpoint    0.117758
14           T8    0.101995
5          RH_3    0.096048
11         RH_6    0.038049
21    Windspeed    0.029183
6            T4    0.028981
7          RH_4    0.026386
9          RH_5    0.016006
22   Visibility    0.012307
12           T7    0.010319
19  Press_mm_hg    0.006839
25          rv2    0.000770
24          rv1    0.000770
0            T1   -0.003281
8            T5   -0.015657
17         RH_9   -0.039800
13         RH_7   -0.044614
20       RH_out   -0.077671
15         RH_8   -0.157595
16           T9   -0.189941
2            T2   -0.236178
18        T_out   -0.321860
3          RH_2   -0.456698


In [97]:
y_pred = reg.predict(x_test)

In [98]:
from sklearn.metrics import mean_squared_error

rmse_2 = np.sqrt(mean_squared_error(y_test,y_pred))

In [105]:
print(round(rmse_2,4))

0.0875


In [100]:
#q18

from sklearn.linear_model import Ridge

ridge = Ridge(alpha=0.4)

ridge.fit(x_train,y_train)
ridge_pred=ridge.predict(x_test)

In [101]:
rmse_3 = np.sqrt(mean_squared_error(y_test,ridge_pred))

In [106]:
print(round(rmse_3,4))

0.0875


In [107]:
#q19

from sklearn.linear_model import Lasso

lasso = Lasso(alpha=0.001)
lasso.fit(x_train,y_train)

Lasso(alpha=0.001)

In [108]:
lasso.coef_

array([ 0.        ,  0.01787993,  0.        , -0.        ,  0.        ,
        0.        , -0.        ,  0.        , -0.        ,  0.        ,
        0.        , -0.        , -0.        , -0.        ,  0.        ,
       -0.00011004, -0.        , -0.        ,  0.        , -0.        ,
       -0.04955749,  0.00291176,  0.        ,  0.        , -0.        ,
       -0.        ])

In [109]:
#q20

lasso_pred = lasso.predict(x_test)

In [112]:
rmse_4 = np.sqrt(mean_squared_error(y_test,lasso_pred))
print(rmse_4)
print(round(rmse_4,3))

0.09358170467245137
0.094
